package com.huihuan.eme.domain.db;
// Generated 2016-1-5 22:02:43 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="eme"
)
public class Groups  implements java.io.Serializable {


     private Long id;
     private String groupName;
     private Set<GroupAuthorities> groupAuthoritieses = new HashSet<GroupAuthorities>(0);
     private Set<GroupMembers> groupMemberses = new HashSet<GroupMembers>(0);

    public Groups() {
    }

	
    public Groups(String groupName) {
        this.groupName = groupName;
    }
    public Groups(String groupName, Set<GroupAuthorities> groupAuthoritieses, Set<GroupMembers> groupMemberses) {
       this.groupName = groupName;
       this.groupAuthoritieses = groupAuthoritieses;
       this.groupMemberses = groupMemberses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="group_name", nullable=false, length=50)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="groups")
    public Set<GroupAuthorities> getGroupAuthoritieses() {
        return this.groupAuthoritieses;
    }
    
    public void setGroupAuthoritieses(Set<GroupAuthorities> groupAuthoritieses) {
        this.groupAuthoritieses = groupAuthoritieses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="groups")
    public Set<GroupMembers> getGroupMemberses() {
        return this.groupMemberses;
    }
    
    public void setGroupMemberses(Set<GroupMembers> groupMemberses) {
        this.groupMemberses = groupMemberses;
    }




}


